# Generated by Django 5.2 on 2025-04-20 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafica", "0001_initial"),
        ("logistica", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Automezzo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("targa", models.CharField(max_length=7)),
                ("marca", models.CharField(max_length=200)),
                ("modello", models.CharField(max_length=200)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="media/media"),
                ),
                ("data_revisione", models.DateField()),
                (
                    "alimentazione",
                    models.CharField(
                        choices=[
                            ("Benzina", "Benzina"),
                            ("Elettrica", "Elettrica"),
                            ("Gasolio", "Gasolio"),
                            ("Metano", "Metano"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data_acquisto", models.DateField()),
                (
                    "valore_acquisto",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("data_alienazione", models.DateField(blank=True, null=True)),
                ("alienato", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CartaCarburante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("limite", models.FloatField()),
                ("residuo", models.FloatField(blank=True, null=True)),
                (
                    "fornitore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anagrafica.fornitori",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MagazzinoMezzo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_entrata", models.DateField(blank=True, null=True)),
                ("data_uscita", models.DateField(blank=True, null=True)),
                (
                    "giacenza",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "mezzo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automezzi.automezzo",
                    ),
                ),
                (
                    "prodotto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistica.products",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManutenzioneMezzi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_intervento", models.DateField(blank=True, null=True)),
                (
                    "intervento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Allestimento", "Allestimento"),
                            ("Cambio Filtri", "Cambio Filtri"),
                            ("Cambio Gomme", "Cambio Gomme"),
                            ("Cambio Olio", "Cambio Olio"),
                            ("Carrozzeria", "Carrozzeria"),
                            ("Elettrauto", "Elettrauto"),
                            ("Lavaggio", "Lavaggio"),
                            ("Revisione", "Revisione"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "costo_intervento",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("note", models.TextField(blank=True, max_length=400, null=True)),
                ("ora", models.TimeField(blank=True, null=True)),
                (
                    "fornitore",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anagrafica.fornitori",
                    ),
                ),
                (
                    "mezzo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automezzi.automezzo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rifornimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(auto_now=True)),
                ("importo", models.FloatField()),
                ("residuo", models.FloatField(blank=True, null=True)),
                (
                    "carta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automezzi.cartacarburante",
                    ),
                ),
                (
                    "mezzo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automezzi.automezzo",
                    ),
                ),
            ],
        ),
    ]
