# Generated by Django 5.2 on 2025-04-20 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Azienda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ragioneSociale", models.CharField(max_length=200)),
                ("indSedeLegale", models.CharField(max_length=200)),
                ("cittaLegale", models.CharField(max_length=200)),
                ("provincia", models.CharField(max_length=2)),
                ("capLegale", models.IntegerField()),
                ("PI", models.CharField(max_length=11)),
                ("CF", models.CharField(max_length=16)),
                ("CU", models.CharField(max_length=7)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Azienda unica", "Azienda unica"),
                            ("Condominio", "Condominio"),
                            ("Multifiliale", "Multifiliale"),
                        ],
                        default="Azienda unica",
                        max_length=15,
                    ),
                ),
                ("referente", models.CharField(max_length=200)),
                ("telefono", models.CharField(max_length=20)),
                ("pec", models.EmailField(max_length=254)),
                (
                    "mailDirezione",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "mailAmministrazione",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("mailOperativo1", models.EmailField(max_length=254)),
                (
                    "mailOperativo2",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "mailOperativo3",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "modpag",
                    models.CharField(
                        choices=[
                            ("01", "Immediato"),
                            ("30", "30 gg df"),
                            ("60", "60 gg df"),
                            ("90", "90 gg df"),
                        ],
                        default="Immediato",
                        max_length=20,
                    ),
                ),
                (
                    "installato",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fornitori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ragioneSociale", models.CharField(max_length=200)),
                ("indSedeLegale", models.CharField(max_length=200)),
                ("cittaLegale", models.CharField(max_length=200)),
                ("provincia", models.CharField(max_length=2)),
                ("capLegale", models.IntegerField()),
                ("PI", models.IntegerField()),
                ("CF", models.CharField(max_length=16)),
                ("CU", models.CharField(max_length=7)),
                ("referente", models.CharField(max_length=200)),
                ("telefono", models.CharField(max_length=20)),
                ("pec", models.EmailField(max_length=254)),
                (
                    "mailDirezione",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "mailAmministrazione",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("mailOperativo1", models.EmailField(max_length=254)),
                (
                    "mailOperativo2",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "mailOperativo3",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Privati",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_cognome", models.CharField(max_length=200)),
                ("parente1", models.CharField(blank=True, max_length=200, null=True)),
                ("parente2", models.CharField(blank=True, max_length=200, null=True)),
                ("indirizzo", models.CharField(max_length=200)),
                ("citta", models.CharField(max_length=200)),
                ("provincia", models.CharField(max_length=2)),
                ("cap", models.CharField(max_length=200)),
                ("telefono_cliente", models.CharField(max_length=20)),
                (
                    "telefono_parente1",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "telefono_parente2",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "installato",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Filiali",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomeFiliale", models.CharField(max_length=200)),
                ("indFiliale", models.CharField(max_length=200)),
                ("cittaFiliale", models.CharField(max_length=200)),
                ("capFiliale", models.CharField(max_length=5)),
                ("telFiliale", models.CharField(max_length=200)),
                ("mailFiliale", models.CharField(max_length=200)),
                (
                    "referenteFiliale",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "installato",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "anaFiliale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anagrafica.azienda",
                    ),
                ),
            ],
        ),
    ]
