# Generated by Django 5.2 on 2025-04-20 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafica", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contratto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_contratto",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data", models.DateField(auto_now_add=True)),
                (
                    "tipo_servizio",
                    models.CharField(
                        choices=[
                            ("derattizzazione", "derattizzazione"),
                            ("deblattizzazione", "deblattizzazione"),
                            ("deformicazione", "deformicazione"),
                            ("giardinaggio", "giardinaggio"),
                            ("disinfestazione", "disinfestazione"),
                            ("rimozione guano", "rimozione_guano"),
                            ("rimozione_carcasse", "rimozione_carcasse"),
                            ("mosche", "mosche"),
                            ("antitarlo", "antitarlo"),
                        ],
                        max_length=50,
                    ),
                ),
                ("prezzo", models.FloatField()),
                ("area_coperta", models.IntegerField(blank=True, null=True)),
                ("condomini", models.IntegerField(blank=True, null=True)),
                (
                    "frequenza",
                    models.CharField(
                        choices=[
                            ("settimanale", "settimanale"),
                            ("bisettimanale", "bisettimanale"),
                            ("mensile", "mensile"),
                            ("bimestrale", "bimestrale"),
                            ("trimestrale", "trimestrale"),
                            ("quadrimestrale", "quadrimestrale"),
                            ("semestrale", "semestrale"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "pagamento",
                    models.CharField(
                        choices=[
                            ("pagamento immediato", "pagamento immediato"),
                            (
                                "30 giorni data fattura fine mese",
                                "30 giorni data fattura fine mese",
                            ),
                            (
                                "60 giorni data fattura fine mese",
                                "60 giorni data fattura fine mese",
                            ),
                            (
                                "90 giorni data fattura fine mese",
                                "90 giorni data fattura fine mese",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=4000, null=True)),
                ("inizio_validità", models.DateField(blank=True, null=True)),
                ("scadenza_contratto", models.DateField(blank=True, null=True)),
                (
                    "anagrafica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_query_name="contratto",
                        to="anagrafica.azienda",
                    ),
                ),
            ],
        ),
    ]
