# Generated by Django 5.2 on 2025-04-20 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafica", "0001_initial"),
        ("automezzi", "0001_initial"),
        ("contratti", "0001_initial"),
        ("logistica", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Servizio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_espletazione", models.DateField(blank=True, null=True)),
                (
                    "altro_luogo",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "luogo_effettivo",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("prezzo", models.FloatField(blank=True, null=True)),
                ("inespl", models.BooleanField(default=False)),
                ("incasso", models.BooleanField(default=False)),
                (
                    "importo_incassato",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "Tiposervizio",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Altro", "Altro"),
                            ("Antitarlo", "Antitarlo"),
                            ("Cambio Postazioni Mosche", "Cambio Postazioni Mosche"),
                            ("Deblattizzazione", "Deblattizzazione"),
                            ("Deformicazione", "Deformicazione"),
                            ("Derattizzazione", "Derattizzazione"),
                            ("Disinfestazione", "Disinfestazione"),
                            ("Giardinaggio", "Giardinaggio"),
                            ("Raccolta Carcasse", "Raccolta Carcasse"),
                            ("Rimozione Guano", "Rimozione Guano"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=244, null=True)),
                ("espletato", models.BooleanField(default=False)),
                ("orario_inizio", models.TimeField(blank=True, null=True)),
                (
                    "pdf",
                    models.FileField(blank=True, null=True, upload_to="media/servizi"),
                ),
                ("data_chiusura", models.DateField(blank=True, null=True)),
                (
                    "azienda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anagrafica.azienda",
                    ),
                ),
                (
                    "contratto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratto",
                        to="contratti.contratto",
                    ),
                ),
                (
                    "filiali",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anagrafica.filiali",
                    ),
                ),
                (
                    "privati",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anagrafica.privati",
                    ),
                ),
                (
                    "prodotto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistica.products",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recupero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_creazione", models.DateField(auto_now_add=True, null=True)),
                ("importo_da_recuperare", models.FloatField(blank=True, null=True)),
                ("data", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True, max_length=2000, null=True)),
                ("chiuso", models.BooleanField(default=False)),
                ("data_chiusura", models.DateField(blank=True, null=True)),
                (
                    "servizio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_query_name="serv",
                        to="servizi.servizio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Distinte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(blank=True, null=True)),
                ("chiusura", models.BooleanField(default=False)),
                (
                    "automezzo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automezzi.automezzo",
                    ),
                ),
                (
                    "servizio_di_manutenzione",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automezzi.manutenzionemezzi",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recupero",
                    models.ManyToManyField(
                        blank=True, related_query_name="recupero", to="servizi.recupero"
                    ),
                ),
                (
                    "servizio",
                    models.ManyToManyField(
                        related_name="servizio",
                        related_query_name="ser",
                        to="servizi.servizio",
                    ),
                ),
            ],
        ),
    ]
