# Generated by Django 5.2 on 2025-04-20 02:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafica", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_prodotto", models.CharField(max_length=200)),
                ("Registro_ministero_della_salute", models.TextField()),
                ("note", models.TextField()),
                (
                    "tipo_articolo",
                    models.CharField(
                        choices=[
                            ("Gel", "Gel"),
                            ("Liquido", "Liquido"),
                            ("Polvere", "Polvere"),
                            ("Singolo Prodotto", "Singolo Prodotto"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "misura",
                    models.CharField(
                        choices=[
                            ("Articolo", "Articolo"),
                            ("Grammi per Articolo", "Grammi per Articolo"),
                            ("Litro", "Litro"),
                            ("Millilitri per Articolo", "Millilitri per Articolo"),
                        ],
                        max_length=50,
                    ),
                ),
                ("prezzo", models.FloatField(blank=True, default=0, null=True)),
                (
                    "fornitore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anagrafica.fornitori",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_articoli", models.FloatField()),
                ("prezzo_singolo_articolo", models.FloatField()),
                ("data_ordine", models.DateField(auto_now_add=True)),
                ("data_arrivo_ordine", models.DateField()),
                ("indirizzo_consegna", models.CharField(max_length=300)),
                ("pagamento", models.CharField(blank=True, max_length=200, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("ricevuto", models.BooleanField(default=False)),
                ("data_ricezione", models.DateField(blank=True, null=True)),
                ("importo_ordine", models.FloatField(blank=True, null=True)),
                ("articoli_ricevuti", models.FloatField(blank=True, null=True)),
                (
                    "pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="media/ordini-acquisto"
                    ),
                ),
                ("pagato", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "fornitore",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anagrafica.fornitori",
                    ),
                ),
                (
                    "prodotto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistica.products",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Install",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_installazione",
                    models.DateField(
                        default=datetime.datetime(
                            2025, 4, 20, 2, 22, 50, 780648, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("quantità", models.PositiveIntegerField(blank=True, null=True)),
                ("cartelli", models.IntegerField(blank=True, null=True)),
                ("totale_postazioni", models.IntegerField(default=0)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="media/installazioni"
                    ),
                ),
                (
                    "azienda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="azienda",
                        to="anagrafica.azienda",
                    ),
                ),
                (
                    "filiale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anagrafica.filiali",
                    ),
                ),
                (
                    "privato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anagrafica.privati",
                    ),
                ),
                (
                    "prodotto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistica.products",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_entrata", models.DateField(blank=True, null=True)),
                ("data_uscita", models.DateField(blank=True, null=True)),
                ("giacenza", models.FloatField(blank=True, null=True)),
                (
                    "bolla_ingresso_merci",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/documenti_merci_in_entrata",
                    ),
                ),
                ("soglia_giacenza", models.FloatField(default=10)),
                (
                    "ordine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistica.order",
                    ),
                ),
                (
                    "prodotto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistica.products",
                    ),
                ),
            ],
        ),
    ]
