# Generated by Django 5.2 on 2025-04-20 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistica", "0002_alter_install_data_installazione"),
    ]

    operations = [
        migrations.AlterField(
            model_name="install",
            name="data_installazione",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 4, 20, 6, 30, 27, 75028, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
