# Generated by Django 5.2 on 2025-04-20 02:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("iban", models.CharField(max_length=27)),
                ("indirizzo", models.CharField(blank=True, max_length=200, null=True)),
                ("cap", models.CharField(blank=True, max_length=5, null=True)),
                ("città", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cassa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("causale", models.CharField(blank=True, max_length=1500, null=True)),
                ("data", models.DateField(blank=True, null=True)),
                ("cassaavere", models.FloatField(blank=True, default=0, null=True)),
                ("cassadare", models.FloatField(blank=True, default=0, null=True)),
                (
                    "aggiungifile",
                    models.FileField(
                        blank=True, null=True, upload_to="media/contabilità"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FatturaAttiva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_fattura", models.DateField(default=datetime.datetime.now)),
                ("imponibile", models.FloatField()),
                ("importoiva", models.FloatField(default=0)),
                ("totale", models.FloatField(blank=True, default=0, null=True)),
                ("descrizione", models.TextField(max_length=4000)),
                ("da_incassare", models.BooleanField(default=True)),
                ("data_scadenza", models.DateField(blank=True, null=True)),
                ("data_pagamento", models.DateField(blank=True, null=True)),
                ("avere", models.FloatField(blank=True, null=True)),
                ("dare", models.FloatField(blank=True, null=True)),
                (
                    "pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="contabilità/fattureattive/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FatturaPassiva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_fattura", models.DateField()),
                ("numero_fattura", models.CharField(default="", max_length=50)),
                ("imponibile", models.FloatField()),
                (
                    "iva",
                    models.FloatField(
                        choices=[(4.0, 4.0), (5.0, 5.0), (10.0, 10.0), (22.0, 22.0)],
                        default=22.0,
                    ),
                ),
                ("descrizione", models.TextField(max_length=10000)),
                ("da_pagare", models.BooleanField(default=True)),
                ("data_pagamento", models.DateField(blank=True, null=True)),
                ("totale", models.FloatField(default=0)),
                ("avere", models.FloatField(blank=True, null=True)),
                ("dare", models.FloatField(blank=True, null=True)),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/contabilità/fatturepassive",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movimenti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("causale", models.CharField(max_length=1000)),
                ("importo", models.FloatField(blank=True, null=True)),
                (
                    "aggiungifile",
                    models.FileField(
                        blank=True, null=True, upload_to="media/contabilità"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NumeroCassa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Versamenti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("causale", models.CharField(max_length=200)),
                ("data", models.DateField()),
                ("dare", models.FloatField()),
                ("avere", models.FloatField()),
                ("object_id", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="BancaMovimenti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("causale", models.CharField(blank=True, max_length=1500, null=True)),
                ("data", models.DateField(blank=True, null=True)),
                ("avere", models.FloatField(blank=True, null=True)),
                ("dare", models.FloatField(blank=True, null=True)),
                (
                    "aggiungifile",
                    models.FileField(
                        blank=True, null=True, upload_to="media/contabilità"
                    ),
                ),
                (
                    "banca",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contabilità.banca",
                    ),
                ),
            ],
        ),
    ]
