# Generated by Django 5.2 on 2025-04-20 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafica", "0001_initial"),
        ("contabilità", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("logistica", "0001_initial"),
        ("servizi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cassa",
            name="servizio",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="servizi.servizio",
            ),
        ),
        migrations.AddField(
            model_name="fatturaattiva",
            name="azienda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="anagrafica.azienda",
            ),
        ),
        migrations.AddField(
            model_name="fatturaattiva",
            name="fornitori",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="anagrafica.fornitori",
            ),
        ),
        migrations.AddField(
            model_name="fatturaattiva",
            name="privato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="anagrafica.privati",
            ),
        ),
        migrations.AddField(
            model_name="cassa",
            name="fattureattiva",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contabilità.fatturaattiva",
            ),
        ),
        migrations.AddField(
            model_name="bancamovimenti",
            name="fattureattiva",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contabilità.fatturaattiva",
            ),
        ),
        migrations.AddField(
            model_name="fatturapassiva",
            name="fornitori",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="anagrafica.fornitori",
            ),
        ),
        migrations.AddField(
            model_name="fatturapassiva",
            name="ordini_acquisto",
            field=models.ManyToManyField(to="logistica.order"),
        ),
        migrations.AddField(
            model_name="cassa",
            name="fatturapassiva",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contabilità.fatturapassiva",
            ),
        ),
        migrations.AddField(
            model_name="bancamovimenti",
            name="fatturapassiva",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contabilità.fatturapassiva",
            ),
        ),
        migrations.AddField(
            model_name="movimenti",
            name="banca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banca",
                to="contabilità.banca",
            ),
        ),
        migrations.AddField(
            model_name="movimenti",
            name="fattura_attiva",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contabilità.fatturaattiva",
            ),
        ),
        migrations.AddField(
            model_name="movimenti",
            name="fattura_passiva",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contabilità.fatturapassiva",
            ),
        ),
        migrations.AddField(
            model_name="movimenti",
            name="cassa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cassa",
                to="contabilità.numerocassa",
            ),
        ),
        migrations.AddField(
            model_name="cassa",
            name="numero_cassa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cax",
                to="contabilità.numerocassa",
            ),
        ),
        migrations.AddField(
            model_name="versamenti",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddIndex(
            model_name="versamenti",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="contabilità_content_4c2c86_idx",
            ),
        ),
    ]
